name: Release
on:
  push:
    branches:
      - main
      # Add any backport branches here that should also be released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout branch
      - uses: actions/checkout@v2
      - name: 'Android autobump version'
      - uses: 'MattiaFailla/android-version-autobump-action@main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'