name: Release
on:
  push:
    branches:
      - main
      # Add any backport branches here that should also be released

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout branch
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get Android version
        id: test
        uses: ltDino/android-get-version-action@v1.0
        with:
          gradlePath: app/build.gradle # or app/build.gradle.kts 
      # - name: Get old version
      #   run: |
      #     echo "The versionCode was ${{ steps.test.outputs.versionCode }}"
      #     echo "The versionName was ${{ steps.test.outputs.versionName }}"
      - name: 'Android autobump version'
        uses: 'MattiaFailla/android-version-autobump-action@main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target-branch: 'main'
          commit-message: 'CI: bumps version to {{version}} [skip ci]'

