name: Release
on:
  push:
    branches:
      - main
      # Add any backport branches here that should also be released

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # PRIVATE_DEPLOY_KEY is the private rsa key, the public key is configured as a deploy key in the repo settings
          # This allows commits and tags to be pushed back to main (a protected branch)
          ssh-key: ${{ secrets.PRIVATE_DEPLOY_KEY }}
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle # or app/build.gradle.kts
          versionCode: ${{github.run_number}}
          versionName: 1.0.0
      - name: Publish
        id: publish
        run: |
          git add .
          git commit -m "version incremented"
          git push
          git tag "`${{github.run_number}}`"
          git push --tags